name: Test with Nondex 2
run-name: Known Flaky test 2
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: 
          mvn -pl hadoop-hdfs-project/hadoop-hdfs-httpfs test -Dtest=org.apache.hadoop.test.TestHFSTestCase.waitForTimeOutRatio1
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: 
          mvn -pl hadoop-hdfs-project/hadoop-hdfs-httpfs edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.hadoop.test.TestHFSTestCase.waitForTimeOutRatio1
